name: Release

on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: BigWigsMods/packager@v1.0.1
        with:
          args: -g retail

      - uses: BigWigsMods/packager@v1.0.1
        with:
          args: -g classic

      - uses: BigWigsMods/packager@v1.0.1
        with:
          args: -g bcc
